microsoft/azure-maven-archetypes

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
=> release 1.1

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/src/main/java/Function.java, azure-functions-archetype/src/main/resources/archetype-resources/src/test/java/FunctionTest.java, pom.xml
- update to Azure Functions Maven Plugin@0.1.6
- update code template to support query string
=> update maven plugin to 0.1.6

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/src/main/java/Function.java, pom.xml
- use version range for functions core packags
- update maven plugin to 0.1.7
=> use version range for functions core packages

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/src/main/java/Function.java, azure-functions-archetype/src/main/resources/archetype-resources/src/test/java/FunctionTest.java, pom.xml
Update the function archetype to align with the new runtime
=> Update the function archetype to align with the new runtime

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
This update contains 2 PR for maven azure-function plugin:
- https://github.com/Microsoft/azure-maven-plugins/pull/69
- https://github.com/Microsoft/azure-maven-plugins/pull/70
=> update maven plugin version to 0.1.9

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
=> add maven dependency plugin to the function archetype

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
=> add the ability to copy the bin folder into the staging directory

azure-functions-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
=> add the ability to specify resource group

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
- bump archetype version to 1.10
- updete plugin dependency version to 1.0.0
- update azure-functions-java-core version to 1.0.0-beta-3
- exclude azure-functions-java-core when copy dependencies
=> bump version

azure-functions-archetype/src/main/resources/archetype-resources/src/main/java/Function.java, azure-functions-archetype/src/main/resources/archetype-resources/src/test/java/FunctionTest.java
=> Update function name

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/src/main/java/Function.java, azure-functions-archetype/src/main/resources/archetype-resources/src/test/java/FunctionTest.java
@pragnagopa Please help review.
BTW, I cannot local run this function using azure-functions-core-tools:2.0.1-beta.30
Do you know any method to verify this change?
=> update source according to the change of new runtime

azure-functions-archetype/src/main/resources/archetype-resources/local.settings.json
=> add worker runtime in local.settings.json

azure-functions-archetype/src/main/resources/archetype-resources/.gitignore
=> add gitignore

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/src/main/java/Function.java, azure-functions-archetype/src/main/resources/archetype-resources/src/test/java/FunctionTest.java
This reverts commit 6a0470e4bbc74532eaabc62b8a04aff64d32f6dc.
=> Revert "update source according to the change of new runtime (#29)"

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/src/main/java/Function.java, azure-functions-archetype/src/main/resources/archetype-resources/src/test/java/FunctionTest.java
Update to azure-functions-library v1.0.0-beta-5
=> Update to azure-functions-library v1.0.0-beta-5

azure-iot-edge-archetype/README.md, azure-iot-edge-archetype/pom.xml, azure-iot-edge-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, azure-iot-edge-archetype/src/main/resources/archetype-resources/.dockerignore, azure-iot-edge-archetype/src/main/resources/archetype-resources/.gitignore, azure-iot-edge-archetype/src/main/resources/archetype-resources/Dockerfile.amd64, azure-iot-edge-archetype/src/main/resources/archetype-resources/Dockerfile.amd64.debug, azure-iot-edge-archetype/src/main/resources/archetype-resources/Dockerfile.arm32v7, azure-iot-edge-archetype/src/main/resources/archetype-resources/Dockerfile.arm32v7.debug, azure-iot-edge-archetype/src/main/resources/archetype-resources/module.json, azure-iot-edge-archetype/src/main/resources/archetype-resources/pom.xml, azure-iot-edge-archetype/src/main/resources/archetype-resources/src/main/java/App.java, azure-iot-edge-archetype/src/main/resources/archetype-resources/src/main/resources/log4j2.xml
amd64 /debug, arm32v7 /debug are supported
=> Add azure iot edge archetype

azure-functions-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
Add validation for groupId and artifactId in azure functions archetype for issue #47
=> Add validation for groupId and artifactId in azure functions archetype.

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Update maven plugin to 1.0.0-beta-6
=> Update maven plugin

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
=> Update FUNCTIONS_EXTENSION_VERSION from beta to ~2

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Update maven plugin to 1.0.0-beta-7
=> Update maven plugin to 1.0.0-beta-7

azure-functions-archetype/pom.xml, pom.xml
Bump version for next release.
=> Bump version for next release.

azure-functions-archetype/src/main/resources/archetype-resources/local.settings.json
=> Removing AzureWebJobsDashboard

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
change default deploy method to run from package
=> change default deploy method to run from package

azure-functions-archetype/pom.xml, azure-iot-edge-archetype/pom.xml, pom.xml
Update pom to release snapshot
=> Update pom to release snapshot

azure-functions-archetype/src/main/resources/archetype-resources/src/test/java/FunctionTest.java
Add SuppressWarnings to avoid warning, to solve issue #84
=> Add SuppressWarnings to avoid warning

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
=> Update maven plugin to 1.2.0

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Update function java lib to 1.2.0
=> Update function java lib to 1.2.0

appveyor_function_e2e.yml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, e2etest.ps1
Add e2e test for plugin archetype, for issue #78
=> Add e2e test for plugin archetype

appveyor_function_e2e.yml, e2etest.ps1
=> Add e2etest for archetype

azure-functions-archetype/src/main/resources/archetype-resources/src/main/java/Function.java
=> Split the comments for it is too long

azure-functions-archetype/pom.xml, pom.xml
=> Bump version for next release

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Update function java lib to 1.2.2, for issue https://github.com/Microsoft/azure-maven-plugins/issues/518
=> Update function java lib to 1.2.2

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/src/test/java/FunctionTest.java
Also updated to latest Mockito.
=> Move to JUnit 5

azure-functions-archetype/README.md
Fix typo in function archetype readme
=> Fix typo in readme

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
=> Prepare for release

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Update maven plugin version for release
=> Update maven plugin version for release

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
Bump function and archetype version
=> Bump function and archetype version

azure-functions-archetype/README.md, azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/META-INF/archetype-post-generate.groovy, azure-functions-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, azure-functions-archetype/src/main/resources/archetype-resources/Dockerfile, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
1. Remove azure attributes in `archetype:generate`, write default values to `pom.xml` directly with comments
2. Add `DockerFile`, which will generated only if user specify `-Ddocker`
=> Support linux and doker function

azure-functions-archetype/src/main/resources/archetype-resources/pom-docker.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Add default app service plan name
=> Add default app service plan name

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Update maven plugin version to 1.4.1
=> Update maven plugin version

appveyor_function_e2e.yml, e2etest.ps1
=> Update CI script

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/Dockerfile, azure-functions-archetype/src/main/resources/archetype-resources/pom-docker.xml
Update docker file and pricing tier for docker support
=> Update docker file and pricing tier for docker support

azure-functions-archetype/src/main/resources/META-INF/archetype-post-generate.groovy, azure-functions-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom-docker.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Add azure parameters back for batch mode
=> Add azure parameters back for batch mode

azure-functions-archetype/README.md, azure-functions-archetype/src/main/resources/archetype-resources/pom-docker.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/src/main/java/Function.java
Fix function archetype code style, refers https://github.com/Azure-Samples/azure-functions-samples-java/pull/9
=> Fix function archetype code style

azure-functions-archetype/pom.xml, pom.xml
Bump function archetype version to 1.27 for release
=> Bump version for release

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/Dockerfile, azure-functions-archetype/src/main/resources/archetype-resources/pom-docker.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
- Add configuration template for java runtime
- Update function docker file
=> Update Azure Function archetype for new feature

azure-functions-archetype/README.md, azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/META-INF/archetype-post-generate.groovy, azure-functions-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, azure-functions-archetype/src/main/resources/archetype-resources/Dockerfile, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Add java version parameters and provide more support for java 11
=> Add java version parameters and provide more support for java 11

azure-functions-archetype/pom.xml, pom.xml
Remove SNAPSHOT and bump version
=> Remove SNAPSHOT and bump version

azure-functions-archetype/src/main/resources/archetype-resources/pom-docker.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Update function plugin version in archetype
=> Update function plugin version in archetype

azure-functions-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
Always set `<javaVersion>` and `<java.version>` according to archetype parameter `javaVersion`, fixes https://github.com/microsoft/azure-maven-archetypes/issues/154
=> Fix java version parameter issue

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom-docker.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
Bump azure function maven plugin version in archetype for release
=> Bump azure function maven plugin version in archetype for release

azure-functions-archetype/README.md
Update function archetype quick start, fixes https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/7494464
=> Update function archetype quick start

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom-docker.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
- Remove SNAPSHOT
- Bump function maven plugin to 1.9.0, bump azure function java library to 1.4.0
=> Remove SNAPSHOT and bump version for release

azure-functions-archetype/README.md, azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/META-INF/archetype-post-generate.groovy, azure-functions-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, pom.xml
Support specify trigger type in archetype, and generate correspond trigger with `azure-functions:add`
=> Support specify trigger type in archetype

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom-docker.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
Bump version to release function archetype 1.36
=> Bump version to release function archetype 1.36

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom-docker.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
Bump version for maven plugin 1.10.1 hot fixes
=> Bump version for maven plugin 1.10.1 hot fixes

azure-functions-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
Support `RabbitMQTrigger` in `-Dtrigger`
=> Support `RabbitMQTrigger` in `-Dtrigger`

azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Remove maven resource and dependency plugin in functions archetype
=> Remove maven resource and dependency plugin in functions archetype

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Remove snapshot for function archetype 1.38, prepare for release
=> Remove snapshot, prepare for release

azure-functions-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
=> Remove timeout in archetype

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Bump archetype and maven plugin version for release
=> Bump archetype and maven plugin version for release

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
Bump version for archetype and maven plugin, prepare for release
=> Bump version for archetype and maven plugin, prepare for release

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
Bump functions maven plugin version to 1.14.1, prepare for release
=> Bump functions maven plugin version to 1.14.1, prepare for release

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
Bump version for functions maven plugin and archetype, prepare for release
=> Bump version for functions maven plugin and archetype, prepare for release

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/Dockerfile, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Update function extension version to ~4
=> Update function extension version to ~4

azure-functions-archetype/src/main/resources/archetype-resources/Dockerfile, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Change default function extension version to ~3, as compatibility issues, refers https://github.com/Azure/azure-functions-host/issues/8119
=> Change default function extension version to ~3

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
Bump version for functions maven plugin to 1.7.0 and java library to 2.0.0, prepare for release
=> Bump version for functions maven plugin and java library

azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/archetype-resources/host.json, pom.xml
- Bump default function bundle version to 3.*, for #182
- Bump version of function archetype, prepare for release
=> Endgame 202207

azure-functions-archetype/README.md, azure-functions-archetype/src/main/resources/archetype-resources/Dockerfile, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml
Fix java 17 support in functions archetype
=> Fix java 17 support in functions archetype

azure-functions-archetype/README.md, azure-functions-archetype/pom.xml, azure-functions-archetype/src/main/resources/META-INF/archetype-post-generate.groovy, azure-functions-archetype/src/main/resources/archetype-resources/host.json, azure-functions-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
- Support create Durable Function with `-Dtrigger` in archetype
- Add required dependencies for rabbitmq/durable functions in archetype
=> Support new templates with functions extension bundle v4
